<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rest-Full App</title>
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_196x196.png" rel="icon" size="196x196" type="image/png">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_96x96.png" rel="icon" size="96x96" type="image/png">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_32x32.png" rel="icon" size="32x32" type="image/png">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_16x16.png" rel="icon" size="16x16" type="image/png">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_128x128.png" rel="icon" size="128x128" type="image/png">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_57x57.png" rel="apple-touch-icon" size="57x57">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_114x114.png" rel="apple-touch-icon" size="114x114">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_72x72.png" rel="apple-touch-icon" size="72x72">
    <meta name="msapplication-TileImage" content="<?= $domain; ?>/webroot/favicons/error/favicon_144x144.png">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_60x60.png" rel="apple-touch-icon" size="60x60">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_120x120.png" rel="apple-touch-icon" size="120x120">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_76x76.png" rel="apple-touch-icon" size="76x76">
    <link href="<?= $domain; ?>/webroot/favicons/error/favicon_152x152.png" rel="apple-touch-icon" size="152x152">
    <meta name="msapplication-square70x70logo" content="<?= $domain; ?>/favicons/error/favicon_70x70.png">
    <meta name="msapplication-square150x150logo" content="<?= $domain; ?>/favicons/error/favicon_150x150.png">
    <meta name="msapplication-square310x310logo" content="<?= $domain; ?>/favicons/error/favicon_310x310.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="<?= $domain; ?>/favicons/error/favicon-144.png">
    <meta name="msapplication-config" content="<?= $domain; ?>/favicons/error/browserconfig.xml">
    <link href="<?= $domain; ?>/webroot/css/error.css" rel="stylesheet">
</head>
<body id="corpo">
<div class="errorTitle">
    <h1><?= $msg; ?></h1>
</div>
<?php
$a = 0;
$traces = array_reverse($traces);
$args = array_reverse($args);
foreach ($traces as $trace) {
    $errorTrace[] = "<a href='#' class='badge linkjs' data-target='way-" . $a . "'><span>" . substr(
            $trace,
            0,
            strpos($trace, " - ")
        ) . "</span><br><span>" . substr($trace, strpos($trace, " - ") + 3) . "</span></a>";
    $keys = array_keys($args[substr($trace, 0, strpos($trace, " - "))]['line']);
    $arguments = [];
    $count = count($keys);
    for ($b = 0; $b < $count; $b++) {
        $paddingLeft = 3 - (strlen($keys[$b]) < 6 ? strlen($keys[$b]) * 0.5 : 0);
        $active = '';
        if ($args[substr($trace, 0, strpos($trace, " - "))]['identify'] === $keys[$b]) {
            $active = ' cols-3-active';
        }
        $arguments[] = "<div class='row-info'><div class='cols-3" . $active . "'>" . $keys[$b] . "</div><div class='cols-12'>" . $args[substr(
                $trace,
                0,
                strpos($trace, " - ")
            )]['line'][$keys[$b]] . "</div></div>";
        if ($b === Count($keys) - 1) {
            $disabled = '';
            if ($a != 0) {
                $disabled = ' cols-7-disabled';
            }
            $errorArgs[] = "<div class='border" . $disabled . "' id='way-" . $a . "'>" . implode(
                    "",
                    $arguments
                ) . "</div>";
        }
    }
    $a++;
}
?>
<div class='row-error'>
    <div class='cols-5'>
        <?= implode("<br>", $errorTrace); ?>
    </div>
    <div class='cols-7'>
        <?= implode("", $errorArgs); ?>
    </div>
</div>
<script src="<?= $domain; ?>/webroot/js/error.js"></script>
<script>
    var auth = '';
    var action = 'error';
</script>
</body>
</html>